In [1]:
pip install faker

Requirement already satisfied: faker in c:\users\ronita karmakar\appdata\local\programs\python\python314\lib\site-packages (40.1.0)
Requirement already satisfied: tzdata in c:\users\ronita karmakar\appdata\local\programs\python\python314\lib\site-packages (from faker) (2025.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import random

from faker import Faker
from datetime import datetime, timedelta

In [4]:
fake = Faker("en_IN")

In [3]:
random.seed(42)
np.random.seed(42)
Faker.seed(42)

In [5]:
NUM_CUSTOMERS = 10000

occupation_income = {
    "Student": (0, 200000),
    "Teacher": (300000, 800000),
    "Software Engineer": (600000, 1800000),
    "Data Analyst": (500000, 1500000),
    "Doctor": (1000000, 3000000),
    "Business Owner": (800000, 5000000),
    "Government Employee": (400000, 1200000),
    "Accountant": (400000, 1000000),
    "Sales Executive": (300000, 900000),
    "Retired": (150000, 600000)
}

cities = {
    "Kolkata": "West Bengal",
    "Delhi": "Delhi",
    "Mumbai": "Maharashtra",
    "Bengaluru": "Karnataka",
    "Hyderabad": "Telangana",
    "Chennai": "Tamil Nadu",
    "Pune": "Maharashtra",
    "Ahmedabad": "Gujarat",
    "Jaipur": "Rajasthan",
    "Lucknow": "Uttar Pradesh"
}

def get_customer_segment(income):
    
    if income < 500000:
        return "Retail"
    
    elif income <= 1500000:
        return "Premium"
    
    else:
        return "VIP"

In [6]:
print(get_customer_segment(250000))
print(get_customer_segment(850000))
print(get_customer_segment(2200000))

Retail
Premium
VIP

In [7]:
customer_ids = [
    f"C{i:05d}"
    for i in range(1, NUM_CUSTOMERS + 1)
]

customer_ids[:5]

['C00001', 'C00002', 'C00003', 'C00004', 'C00005']

In [8]:
customers = []

for customer_id in customer_ids:

    # Generate Name
    first_name = fake.first_name()
    last_name = fake.last_name()

    # Gender
    gender = random.choices(
        ["Male", "Female", "Other"],
        weights=[49, 49, 2],
        k=1
    )[0]

    # Age between 21 and 70
    age = random.randint(21, 70)

    dob = (
        datetime.today()
        - timedelta(days=age * 365 + random.randint(0, 364))
    ).date()

    # Occupation
    occupation = random.choice(list(occupation_income.keys()))

    # Income based on occupation
    income = random.randint(
        occupation_income[occupation][0],
        occupation_income[occupation][1]
    )

    # Customer Segment
    segment = get_customer_segment(income)

    # City & State
    city = random.choice(list(cities.keys()))
    state = cities[city]

    # Marital Status
    marital_status = random.choices(
        ["Single", "Married", "Divorced", "Widowed"],
        weights=[45, 45, 5, 5],
        k=1
    )[0]

    # Email
    email = (
        first_name.lower()
        + "."
        + last_name.lower()
        + str(random.randint(1,999))
        + "@email.com"
    )

    # Phone
    phone = str(random.randint(6000000000, 9999999999))

    # Join Date
    join_date = fake.date_between(
        start_date="-8y",
        end_date="today"
    )

    # Store Record
    customers.append({
        "Customer_ID": customer_id,
        "First_Name": first_name,
        "Last_Name": last_name,
        "Gender": gender,
        "DOB": dob,
        "Email": email,
        "Phone": phone,
        "City": city,
        "State": state,
        "Occupation": occupation,
        "Annual_Income": income,
        "Marital_Status": marital_status,
        "Customer_Segment": segment,
        "Join_Date": join_date
    })

In [9]:
customers_df = pd.DataFrame(customers)

In [10]:
customers_df.head()

,Customer_ID,First_Name,Last_Name,Gender,DOB,Email,Phone,City,State,Occupation,Annual_Income,Marital_Status,Customer_Segment,Join_Date
0,C00001,Isaac,Bakshi,Male,1972-10-13,isaac.bakshi719@email.com,8340505846,Bengaluru,Karnataka,Student,147127,Married,Retail,2024-11-23
1,C00002,Anvi,Konda,Male,1976-10-19,anvi.konda164@email.com,8998485882,Kolkata,West Bengal,Doctor,2697498,Married,VIP,2020-06-27
2,C00003,Liam,Chaudry,Male,1988-05-26,liam.chaudry390@email.com,6415393687,Chennai,Tamil Nadu,Data Analyst,1300581,Single,Premium,2024-05-06
3,C00004,Gagan,Sami,Male,1982-10-10,gagan.sami550@email.com,6536124280,Kolkata,West Bengal,Doctor,2692670,Married,VIP,2018-11-10
4,C00005,Ayushman,Chander,Female,1981-07-06,ayushman.chander371@email.com,8479708607,Lucknow,Uttar Pradesh,Sales Executive,607419,Married,Premium,2020-06-13

In [11]:
customers_df.shape

(10000, 14)

In [12]:
customers_df["Customer_ID"].duplicated().sum()

np.int64(0)

In [13]:
customers_df["Email"].duplicated().sum()

np.int64(0)

In [14]:
customers_df["Customer_Segment"].value_counts()

Customer_Segment
Premium    5361
Retail     2890
VIP        1749
Name: count, dtype: int64

In [15]:
customers_df["Occupation"].value_counts()

Occupation
Retired                1041
Student                1036
Sales Executive        1033
Teacher                1015
Government Employee    1012
Software Engineer      1000
Data Analyst            981
Accountant              978
Doctor                  963
Business Owner          941
Name: count, dtype: int64

In [17]:
customers_df.isnull().sum()

Customer_ID         0
First_Name          0
Last_Name           0
Gender              0
DOB                 0
Email               0
Phone               0
City                0
State               0
Occupation          0
Annual_Income       0
Marital_Status      0
Customer_Segment    0
Join_Date           0
dtype: int64

In [18]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       10000 non-null  object
 1   First_Name        10000 non-null  object
 2   Last_Name         10000 non-null  object
 3   Gender            10000 non-null  object
 4   DOB               10000 non-null  object
 5   Email             10000 non-null  object
 6   Phone             10000 non-null  object
 7   City              10000 non-null  object
 8   State             10000 non-null  object
 9   Occupation        10000 non-null  object
 10  Annual_Income     10000 non-null  int64
 11  Marital_Status    10000 non-null  object
 12  Customer_Segment  10000 non-null  object
 13  Join_Date         10000 non-null  object
dtypes: int64(1), object(13)
memory usage: 1.1+ MB

In [30]:
customers_df["DOB"] = pd.to_datetime(customers_df["DOB"])
customers_df["Join_Date"] = pd.to_datetime(customers_df["Join_Date"])

In [31]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       10000 non-null  object
 1   First_Name        10000 non-null  object
 2   Last_Name         10000 non-null  object
 3   Gender            10000 non-null  object
 4   DOB               10000 non-null  datetime64[ns]
 5   Email             10000 non-null  object
 6   Phone             10000 non-null  object
 7   City              10000 non-null  object
 8   State             10000 non-null  object
 9   Occupation        10000 non-null  object
 10  Annual_Income     10000 non-null  int64
 11  Marital_Status    10000 non-null  object
 12  Customer_Segment  10000 non-null  object
 13  Join_Date         10000 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(11)
memory usage: 1.1+ MB

In [19]:
customers_df["Annual_Income"].describe()

count    1.000000e+04
mean     9.948678e+05
std      8.976322e+05
min      3.780000e+02
25%      4.580428e+05
50%      7.289985e+05
75%      1.210618e+06
max      4.991973e+06
Name: Annual_Income, dtype: float64

In [20]:
customers_df.groupby("Occupation")["Annual_Income"].agg(["min", "max", "mean"])

                         min      max          mean
Occupation
Accountant            401429   999691  6.985122e+05
Business Owner        800488  4991973  2.857566e+06
Data Analyst          500053  1499773  1.012086e+06
Doctor               1000194  2994922  1.997077e+06
Government Employee   400725  1198925  7.819056e+05
Retired               150352   599909  3.757925e+05
Sales Executive       302088   899899  5.985690e+05
Software Engineer     603727  1799964  1.194737e+06
Student                  378   199899  1.021621e+05
Teacher               300052   799965  5.508714e+05

In [21]:
customers_df["Customer_Segment"].value_counts()

Customer_Segment
Premium    5361
Retail     2890
VIP        1749
Name: count, dtype: int64

In [22]:
customers_df["Customer_Segment"].value_counts(normalize=True) * 100

Customer_Segment
Premium    53.61
Retail     28.90
VIP        17.49
Name: proportion, dtype: float64

In [23]:
customers_df["Occupation"].value_counts()

Occupation
Retired                1041
Student                1036
Sales Executive        1033
Teacher                1015
Government Employee    1012
Software Engineer      1000
Data Analyst            981
Accountant              978
Doctor                  963
Business Owner          941
Name: count, dtype: int64

In [24]:
customers_df["Gender"].value_counts(normalize=True) * 100

Gender
Male      49.23
Female    49.09
Other      1.68
Name: proportion, dtype: float64

In [25]:
customers_df["City"].value_counts()

City
Ahmedabad    1070
Mumbai       1036
Chennai      1021
Hyderabad    1020
Pune          993
Bengaluru     984
Kolkata       984
Delhi         979
Lucknow       959
Jaipur        954
Name: count, dtype: int64

In [26]:
customers_df["Customer_ID"].duplicated().sum()

np.int64(0)

In [27]:
customers_df["Email"].duplicated().sum()

np.int64(0)

In [28]:
customers_df["Phone"].duplicated().sum()

np.int64(0)

In [29]:
customers_df.sample(10)

,Customer_ID,First_Name,Last_Name,Gender,DOB,Email,Phone,City,State,Occupation,Annual_Income,Marital_Status,Customer_Segment,Join_Date
6252,C06253,Ati,Madan,Female,1973-03-16,ati.madan354@email.com,9149221444,Chennai,Tamil Nadu,Retired,411004,Single,Retail,2018-09-25
4684,C04685,Harinakshi,Dhar,Male,1975-07-19,harinakshi.dhar8@email.com,9819339806,Chennai,Tamil Nadu,Software Engineer,1553563,Single,VIP,2026-05-10
1731,C01732,Zashil,Batta,Male,1987-10-08,zashil.batta655@email.com,7471850632,Kolkata,West Bengal,Retired,346617,Single,Retail,2021-12-23
4742,C04743,Vasudha,Varkey,Female,1971-11-17,vasudha.varkey778@email.com,7169416982,Kolkata,West Bengal,Business Owner,3522213,Single,VIP,2021-01-01
4521,C04522,Oviya,Sandhu,Male,1966-10-16,oviya.sandhu834@email.com,8368882595,Jaipur,Rajasthan,Accountant,781992,Married,Premium,2025-03-04
6340,C06341,Rachit,Bal,Male,1989-03-02,rachit.bal990@email.com,6556178987,Chennai,Tamil Nadu,Software Engineer,1472344,Married,Premium,2026-07-14
576,C00577,Maanas,Manne,Female,1967-10-27,maanas.manne565@email.com,7119338568,Bengaluru,Karnataka,Government Employee,1018697,Divorced,Premium,2022-03-29
5202,C05203,Abhiram,Bera,Female,1960-05-24,abhiram.bera503@email.com,7551458182,Kolkata,West Bengal,Retired,295793,Married,Retail,2021-05-29
6363,C06364,Chaitaly,Grewal,Male,2004-06-29,chaitaly.grewal988@email.com,9275744531,Hyderabad,Telangana,Retired,410957,Married,Retail,2024-01-08
439,C00440,Harinakshi,Setty,Male,1999-02-20,harinakshi.setty750@email.com,7876335418,Mumbai,Maharashtra,Doctor,1676547,Widowed,VIP,2021-12-24

In [32]:
customers_df.to_csv(
    "Customers1.csv",
    index=False
)